apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-3mze
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-3mze
    app.kubernetes.io/part-of: tkrw-pr712-0075-0070-app
  name: devfile-sample-3mze
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-3mze
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-3mze
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0070-tenant/tkrw-pr712-0075-0070-app/devfile-sample-3mze@sha256:70b19b48e46b2dfdfd7d379eafdd5fcfa438c508a32709ac173bccb7dc6ae0cf
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
